### ISSUE TITLE
Travis CI build support

### ISSUE THREAD

**Issue by sormuras** [forax/pro#7]
The following `.travis.yml` installs the latest Java 9 version (b162 or higher) and `pro-9-b160` and calls `pro` in the project root directory.

```
sudo: false
dist: trusty

language: java
jdk: oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

before_install:
- wget --no-check-certificate https://github.com/forax/pro/releases/download/v0.9.160/pro-9-b160-linux.tar.gz
- tar -xzf pro-9-b160-linux.tar.gz

install:
- java -version

script:
- ./pro/bin/pro
```

See a log of a successful run at https://travis-ci.org/sormuras/beethoven/builds/216916205

Rémi, feel free to close this non-issue promptly. Just wanted to share my two cents, erm lines back to this wonderful project.

**Comment by forax** [comment]
Feel free to submit a oull request and i will accept it.
and then close this issue as fixed :)

**Comment by sormuras** [comment]
https://github.com/forax/pro-demo or https://github.com/forax/moduletools would be more suitable. That `.travis.yml` uses the pro binary distro to build your "pro'ed" projects.

But, another `.travis.yml` that checks the build state of "pro" itself could be useful as well.

**Comment by forax** [comment]
I agree.
The problem is that there are not enough test.

**Comment by sormuras** [comment]
I use another example project to build and run **pro (master)** (read: test) on Travis with:
```
language: java
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - oracle-java9-installer

jdk: oraclejdk9

install:
# Download pro and build it...
- wget --no-check-certificate https://github.com/forax/pro/archive/master.zip
- unzip master.zip
- cd pro-master
- chmod u+x build.sh
- ./build.sh
- cd ..

script:
- ./pro-master/target/pro/bin/pro
```

See log: https://travis-ci.org/sormuras/application-junit5-jdk9-demo/builds/222332305

PS: You should enable Travis CI at https://travis-ci.org/forax 😉
